export const routes = {
  main: '/main',
  clinicCommentPage: 'home',
  signIn: '/sign-in',
  signUp: '/sign-up',
  adminPage: 'admin',
  clientPage: 'client',
  directorPage: 'director',
  doctorPage: 'doctor',
  nursePage: 'intern',
  employees: 'employees',
  addEmployee: 'add-employee',
  clients: 'clients',
  addClient: 'add-client',
  updateEmployee: 'update-employee',
  addAnimal: 'add-animal',
};
